suppressPackageStartupMessages(library(tidyverse))
library(sf)
data(meuse, package = "sp")
meuse_sf <- meuse %>% as_tibble %>% st_as_sf(coords = c("x", "y"), crs = 28992)
meuse_sf %>% select(c(1:4,13))
nc <- read_sf(system.file("gpkg/nc.gpkg", package="sf"))
options(digits = 4)
options(pillar.sigfig = 4)
nc %>% select(c(4:7, 13))
